### ISSUE TITLE
Temperature not working?

### ISSUE THREAD

**Issue by csachs** [toto/homebridge-aircontrol-mini#2]
Thanks for the plug-in!

Is temperature reporting working with the code as-is?
For me, the Home app shows 0°C …
Changing `new Number(temp)` to `Math.round(temp)` on https://github.com/toto/homebridge-aircontrol-mini/blob/master/main.js#L76 fixes the problem (to show integral temperature values … does HomeKit support floating point temperatures?)

I can open a pull request if desired.

**Comment by csachs** [comment]
Okay, I've taken a closer look, apparently putting it into a `Number` object is the culprit.
Temperature allows 0.1 resolution ( https://github.com/KhaosT/HAP-NodeJS/blob/a4f806d4eccf97cbb4995207e3225937b7622519/lib/gen/HomeKitTypes.js#L684 ).
Replacing `new Number(temp)` with `Number.parseFloat(temp)` does the trick.

(cf. `typeof new Number('123') === 'object' && typeof Number.parseFloat('123') === 'number'`)

**Comment by toto** [comment]
Oh I will fix this. Thanks!

**Comment by toto** [comment]
Should be fixed in curren version
